### PR TITLE
[WIP #1118] fix: add 400 second tag search debounce

### PR DESCRIPTION
**Pull request by prithvidasgupta**
Fix for #1118 

Fixed:
 - Stop hammering the backend with every tag search key stroke ( 400 ms `debounce`)

Fixing:
 - Use old state till the debounce results come back.

### CODE REVIEW

**Comment by shuashuai** [comment]
@prithvidasgupta 

The PR you submitted is shown in Draft status. If you are sure you need to contribute to the PR, please set the PR status to normal first, and then we will review the feature.

**Comment by prithvidasgupta** [comment]
@shuashuai I need to make a few more changes on this (I will do it during the weekend) but I guess I can open it for review.

**Review by shuashuai — APPROVED** [review]
Thank you for your contribution!

**Comment by shuashuai** [comment]
> @shuashuai I need to make a few more changes on this (I will do it during the weekend) but I guess I can open it for review.

It doesn’t matter, you can continue to open a new PR to contribute

**Pull request merged**
