### PR TITLE
fix: License breaks helm chart

### PR DESCRIPTION
**Pull request by sy-records**
fix apache/incubator-answer\#590

### CODE REVIEW

**Comment by mortenbirkelund** [comment]
I was mistaken. The same thing goes for the hpa, pvc and ingress. They are also conditional are are giving the same errors

**Review by LinuxSuRen — COMMENTED** [review]
I'm wondering if it's possible to have a way to test aginst it automatically. For example, doing a lint or a dry run something.

**Comment by LinuxSuRen** [comment]
By the way, test the Helm chart via e2e testing might be a good choice. During the e2e testing, it can install the Helm in k3s or other small Kubernetes distribution.

**Review by tisonkun — APPROVED** [review]
Thank you!

**Pull request merged**
