### PR TITLE
bugfix: fix time format in de-DE

### LINKED ISSUE #391: Upgrade to the latest version (German)
**Describe the bug**

The year is not displayed. In my case for example "Dec 19, JJJJ". In addition, it also does not correspond to the German date format.

Otherwise there are a lot of translation errors. I'll try to revise the language file in the next days - but can't promise it yet.

**Screenshots**

grafik

**Platform (please complete the following information):**
 - Device: Desktop
 - OS: Win 11
 - Browser  all browsers
- Version: latest

### PR DESCRIPTION
**Pull request by xialeistudio**
Bugfix: fix time format in **de-DE**

### CODE REVIEW

**Review by shuashuai — APPROVED** [review]

**Comment by shuashuai** [comment]
> Fixed this issue #391

I have carefully checked the issu #391. This issue describes not only a time issue, but an issue with the entire language file. Therefore, I will not merge your PR for the time being. If you have the ability to translate the entire de language, you are welcome. Come to [crowdin](https://crowdin.com/project/answer) to help us translate and finally complete this PR. Thanks!

**Review by shuashuai — CHANGES_REQUESTED** [review]
The modification is incomplete, you can refer to the comments to supplement it.

**Comment by shuashuai** [comment]
> Fixed this issue #391

Hi,  if you just want to fix the timing problem mentioned in this issu, you can close the isu first, re-initiate the PR, and modify the title and commit information of the response, so that your PR is a complete function and we can merge it. Looking forward to your contribution.

**Comment by xialeistudio** [comment]
> > Fixed this issue #391
> 
> Hi, if you just want to fix the timing problem mentioned in this issu, you can close the isu first, re-initiate the PR, and modify the title and commit information of the response, so that your PR is a complete function and we can merge it. Looking forward to your contribution.

OK, I have modified the title and commit information

**Pull request closed without merging**
