### PR TITLE
refactor Changes - moved legal clicks outside of signup

### PR DESCRIPTION
**Pull request by surapuramakhil**
To enhance reusability - moved this behavior outside so that other components can reuse this.

Testing Everything is running smooth after changes.

### CODE REVIEW

**Comment by surapuramakhil** [comment]
@shuashuai  @robinv8

**Comment by surapuramakhil** [comment]
@shuashuai idea is to have behavioral functions or functions (in a broader sense) that components can reuse.

Leveraging Functional programming.

**Comment by shuashuai** [comment]
> @shuashuai idea is to move out behavioral functions or functions (in a broader sense) from FC so that other FC can reuse.
> 
> Leveraging Functional programming.

Understood, I have been busy with other things these two days, please be patient.

**Comment by shuashuai** [comment]
I found an error, as shown below. （this happens after the jump）

image

Although it does not affect the function, it still needs to be solved, the error lies in the two functions `useLegalTos()` `useLegalPrivacy`, there are two possible solutions to this:

1. encapsulate this function into a hooks.
2. use normal requests, not via SWR.

**Comment by surapuramakhil** [comment]
> encapsulate this function into a hooks.

Made this changes

**Review by shuashuai — APPROVED** [review]

**Pull request merged**
