### PR TITLE
Fix/1.2.0/userprofile (#661)

### PR DESCRIPTION
**Pull request by insistedMarin**
This Pull Request introduces a new filtering functionality to the `userprofile` page. The main objective of this update is to enhance the user experience by providing a more refined control over the visibility of posts.

**Key Changes:**
1. **Filter Implementation for `topData` and `listData`:** The `topData` and `listData` on the `userprofile` page have been updated with a filtering mechanism. This feature filters out 'unlisted' posts, ensuring that they are only visible to specific user roles.

2. **Role-Based Visibility:** The visibility of 'unlisted' posts is now restricted. These posts are only displayed to the Post author, Admin, and Moderator roles. 

**Testing:**
The new filter functionality has been thoroughly tested to ensure it operates as intended across various scenarios. Tests included checking the visibility of posts for different user roles and verifying the correct functioning of the `topData` and `listData` filters.

Looking forward to your feedback and suggestions on this implementation.

Thank you for considering this Pull Request.

Related issue: #661

### CODE REVIEW

**Comment by shuashuai** [comment]
First of all thank you for your contribution!

A good solution should be to adjust the results returned by the corresponding API through token authentication! Calling the details API in batches through the list is not a good solution! 

As developers, we should think more about whether the solution is reasonable! This is a very important concept!

**Comment by insistedMarin** [comment]
Thank you very much for your guidance, I will revisit this issue !

**Comment by shuashuai** [comment]
> Thank you very much for your guidance, I will revisit this issue !

This requires adjusting some logic on the backend. If you need technical support, you can contact @LinkinStars  for help.

**Comment by hgaol** [comment]
if needed, I can help with the backend part. :)

**Comment by insistedMarin** [comment]
> if needed, I can help with the backend part. :)

Many thanks if you can provide any help.

**Pull request closed without merging**
