### PR TITLE
fix(ui): fixed the ui issue of skeleton screen flickering

### PR DESCRIPTION
**Pull request by foxzero-007**
The changes made in this pull request are quite extensive, and the proposed solution is briefly described in the following text. I hope you can take some time to review it when you have a moment.

**What did I modify in this branch?**

Perhaps you have noticed that we have been using the skeleton screen technology on the frontend pages. However, the control over it seems a bit simplistic. We currently only initiate the skeleton screen when entering the page and directly replace it with new nodes upon interface returns. As a result, there is a "skeleton screen flickering" issue during usage. In favorable network conditions, we often observe a quick flash of the skeleton screen. From a user experience perspective, I prefer the page not to change so rapidly. Therefore, I have submitted this pull request to address the issue.

**How did I make the modification?**

Through code comparison, it can be observed that I actually encapsulated a new hook named `useSkeletonControl`. The parameters it returns are as follows:

```ts
{
     isSkeletonShow, // Should the skeleton screen be displayed?
     openSkeleton, // Activate the skeleton screen.
     closeSkeleton // Deactivate the skeleton screen.
}
```

In the code logic, you can see that I have implemented a delay-like operation for both activation and deactivation. The reason behind this is that I believe the opening logic of the skeleton screen should be like this:

- When the interface returns within 1 second, there is no need to activate the skeleton screen.
  
- When the interface takes more than 1 second to return, the skeleton screen is activated, and the activation time should not be less than 3 seconds.
  

(The above-mentioned times are all defined as constants and can be adjusted according to the actual situation.)

Based on this design approach, I utilized `setTimeout` and `clearTimeout` to control the timing of activation and deactivation.

Why provide a `needShowFirst` parameter?

Clearly, this parameter is used to control whether the skeleton screen is rendered right from the start. It allows the skeleton screen to bypass the first timing condition mentioned earlier, meaning it can be activated even if the interface returns in less than 1 second. The reason behind this is that I noticed in some pages, the skeleton screen needs to occupy its position right from the start to prevent the 'flickering' issue on the page. So, I introduced this parameter. However, in my design, I don't intend to show the skeleton screen when the interface response time is too short, as it might negatively impact the user experience.

The above is the reason behind my pull request. I have made modifications for the pages I identified, and I hope they will be accepted. Additionally, if there are better solutions, I am eager to see them. Thanks again for considering my changes.

### CODE REVIEW

**Comment by shuashuai** [comment]
Thank you very much for your contribution. We will first discuss the advantages, disadvantages and necessity of this solution. Please be patient.

**Comment by foxzero-007** [comment]
> Thank you very much for your contribution. We will first discuss the advantages, disadvantages and necessity of this solution. Please be patient.

Ok, thank you for your reply. Look forward to hearing from you.

**Comment by robinv8** [comment]
I understand your thinking, but I think it complicates the problem. I have a suggestion:

Create a Wrapper component, and then use setTimeout to control whether to display the skeleton screen, for example
```
<ListWrapper isLoading={isLoading} loader={<QuestionListLoader/>}>
....
</ListWrapper>
```

**Comment by foxzero-007** [comment]
> I understand your thinking, but I think it complicates the problem. I have a suggestion:
> 
> Create a Wrapper component, and then use setTimeout to control whether to display the skeleton screen, for example
> 
> ```
> <ListWrapper isLoading={isLoading} loader={<QuestionListLoader/>}>
> ....
> </ListWrapper>
> ```

Thank you very much for your response. Here, I would like to share my thoughts.

In fact, whether it's `components` or `hooks`, our core lies in handling the `loading state`. From my understanding, there isn't a particularly significant difference in the implementation of `loading` between the two approaches. Personally, in functional components, I prefer using hooks to manage data exclusively and abstracting the management of the `loading state`'out of the component. In contrast, if we use a `component-based` approach, we need to encapsulate a portion of the `rendering logic`. I am uncertain whether the rendering logic in the `ListWrapper` component will be generic enough to meet all business scenarios in future situations.

**Comment by robinv8** [comment]
> > I understand your thinking, but I think it complicates the problem. I have a suggestion:
> > Create a Wrapper component, and then use setTimeout to control whether to display the skeleton screen, for example
> > ```
> > <ListWrapper isLoading={isLoading} loader={<QuestionListLoader/>}>
> > ....
> > </ListWrapper>
> > ```
> 
> Thank you very much for your response. Here, I would like to share my thoughts.
> 
> In fact, whether it's `components` or `hooks`, our core lies in handling the `loading state`. From my understanding, there isn't a particularly significant difference in the implementation of `loading` between the two approaches. Personally, in functional components, I prefer using hooks to manage data exclusively and abstracting the management of the `loading state` out of the component. In contrast, if we use a `component-based` approach, we need to encapsulate a portion of the `rendering logic`. I am uncertain whether the rendering logic in the `ListWrapper` component will be generic enough to meet all business scenarios in future situations.

I agree with using hooks, but I don’t recommend exposing too much logic to business components. Secondly, the implementation of `useSkeletonControl` is too complicated, and the settings of `SKELETON_SHOW_MIN_TIME` and `SKELETON_NEED_TIME` are also unfounded. Under normal circumstances, the interface The response speed is at the millisecond level and does not need to be so complicated.

**Comment by foxzero-007** [comment]
> > > I understand your thinking, but I think it complicates the problem. I have a suggestion:
> > > Create a Wrapper component, and then use setTimeout to control whether to display the skeleton screen, for example
> > > ```
> > > <ListWrapper isLoading={isLoading} loader={<QuestionListLoader/>}>
> > > ....
> > > </ListWrapper>
> > > ```
> > 
> > 
> > Thank you very much for your response. Here, I would like to share my thoughts.
> > In fact, whether it's `components` or `hooks`, our core lies in handling the `loading state`. From my understanding, there isn't a particularly significant difference in the implementation of `loading` between the two approaches. Personally, in functional components, I prefer using hooks to manage data exclusively and abstracting the management of the `loading state` out of the component. In contrast, if we use a `component-based` approach, we need to encapsulate a portion of the `rendering logic`. I am uncertain whether the rendering logic in the `ListWrapper` component will be generic enough to meet all business scenarios in future situations.
> 
> I agree with using hooks, but I don’t recommend exposing too much logic to business components. Secondly, the implementation of `useSkeletonControl` is too complicated, and the settings of `SKELETON_SHOW_MIN_TIME` and `SKELETON_NEED_TIME` are also unfounded. Under normal circumstances, the interface The response speed is at the millisecond level and does not need to be so complicated.



> > > I understand your thinking, but I think it complicates the problem. I have a suggestion:
> > > Create a Wrapper component, and then use setTimeout to control whether to display the skeleton screen, for example
> > > ```
> > > <ListWrapper isLoading={isLoading} loader={<QuestionListLoader/>}>
> > > ....
> > > </ListWrapper>
> > > ```
> > 
> > 
> > Thank you very much for your response. Here, I would like to share my thoughts.
> > In fact, whether it's `components` or `hooks`, our core lies in handling the `loading state`. From my understanding, there isn't a particularly significant difference in the implementation of `loading` between the two approaches. Personally, in functional components, I prefer using hooks to manage data exclusively and abstracting the management of the `loading state` out of the component. In contrast, if we use a `component-based` approach, we need to encapsulate a portion of the `rendering logic`. I am uncertain whether the rendering logic in the `ListWrapper` component will be generic enough to meet all business scenarios in future situations.
> 
> I agree with using hooks, but I don’t recommend exposing too much logic to business components. Secondly, the implementation of `useSkeletonControl` is too complicated, and the settings of `SKELETON_SHOW_MIN_TIME` and `SKELETON_NEED_TIME` are also unfounded. Under normal circumstances, the interface The response speed is at the millisecond level and does not need to be so complicated.

Thanks for your reply,
I strongly agree that a skeleton screen should not be displayed when the interface returns very quickly. However, currently, we are facing issues with the control strategy for the skeleton screen when the interface response is too fast. This is why I need to implement a more complex solution to control the loading. The meanings of the two parameters mentioned above are as follows:

- `SKELETON_NEED_TIME`:Define when the skeleton screen should be displayed after the interface response exceeds a certain duration.
- `SKELETON_SHOW_MIN_TIME`:The minimum duration for displaying the skeleton screen (I believe the skeleton screen should be maintained for a certain period once displayed to prevent it from flashing too quickly).

When the interface response time is less than `SKELETON_NEED_TIME`, we can directly hide the skeleton screen without displaying it. However, when the response time is greater than `SKELETON_NEED_TIME`, I prefer the skeleton screen to be displayed and maintained for a certain duration. Regarding the current assignments for these two parameters, I've set them arbitrarily. In reality, these values should be determined by UI designers as they represent the user's psychological expectations for response times.

In fact, this logic only delays the switching time of the loading state to achieve control over the display of the skeleton screen. It should not involve any business logic but rather exists purely as a tool. I'm not quite sure about the use of `complicated` in this context as it seems to be a straightforward implementation without intricate business logic.

**Comment by robinv8** [comment]
@foxzero-007 Hello, I have added suggestions for rectification and look forward to your reply.

**Comment by foxzero-007** [comment]
> @foxzero-007 Hello, I have added suggestions for rectification and look forward to your reply.

Thanks for your reply,
I strongly agree that a skeleton screen should not be displayed when the interface returns very quickly. However, currently, we are facing issues with the control strategy for the skeleton screen when the interface response is too fast. This is why I need to implement a more complex solution to control the loading. The meanings of the two parameters mentioned above are as follows:

SKELETON_NEED_TIME:Define when the skeleton screen should be displayed after the interface response exceeds a certain duration.
SKELETON_SHOW_MIN_TIME:The minimum duration for displaying the skeleton screen (I believe the skeleton screen should be maintained for a certain period once displayed to prevent it from flashing too quickly).
When the interface response time is less than SKELETON_NEED_TIME, we can directly hide the skeleton screen without displaying it. However, when the response time is greater than SKELETON_NEED_TIME, I prefer the skeleton screen to be displayed and maintained for a certain duration. Regarding the current assignments for these two parameters, I've set them arbitrarily. In reality, these values should be determined by UI designers as they represent the user's psychological expectations for response times.

In fact, this logic only delays the switching time of the loading state to achieve control over the display of the skeleton screen. It should not involve any business logic but rather exists purely as a tool. I'm not quite sure about the use of complicated in this context as it seems to be a straightforward implementation without intricate business logic.

**Comment by robinv8** [comment]
Hello, thank you very much for your contribution. After discussion with our team, we still need you to make rectifications according to the results of the review, otherwise it will not be merged.

**Comment by foxzero-007** [comment]
@robinv8 Okay, I have simplified the implementation of the hook. Perhaps you can take a look and see if this solution is feasible.

**Comment by robinv8** [comment]
Hello, I have simplified it based on your code, see here
https://github.com/foxzero-007/incubator-answer/pull/1

**Pull request merged**
